@startuml ClassDiagram


class Date {
  int year
  int month
  int day
  int hour
  int minute
}


class Spektakl {
  string tytul
  Date data
  int nr_sali
  int ilosc_miejsc
  string[] aktorzy
  bool wyprzedany
}

class Czlowiek {
  string nazwisko
  string imie
}
class Klient {
  int id 
  string email
  string nr_telefonu
  string adres
  
  void generujBilet(sposob:string)
  zwrocBilet(bilet:Bilet, dane_zwrotu:json):bool
  void uzupelnijDane(adres:string, email:string, imie:strin, nazwisko:string)
  wybierzSpektakl(id_spektaklu:int):Spektakl,dates[]
  wybierzSpektakl(id_aktora:int):Spektakle[]
  wybierzSpektakl(data_spektaklu:date):date,Spektakle[]
  pokazKoszyk():Koszyk
  void otworzStroneGlowna()
}


class Bank {
  int id 
  string nazwa
  string[] metody_platnosci
}

class Platnosc {
  int id 
  float kwota
  int ttl
  int nr_karty
  int cvv 
  string data_waznosci
  int kod_blik
  string nr_konta

  platnoscKarta(kwota:float, nr_karty:int, cvv:int, data_waznosci:date, ttl:int):bool
  platnoscPrzelewem(kwota:float, nr_konta:string, ttl:int):bool
  platnoscBlik(kwota:float, kod_blik:int, ttl:int):bool
}

class Bilet{
  int id 
  int id_spektaklu
  float cena
  string[] miejsca

  kupBilet(bilet:Bilet, sposob_wysylki:string):bool
  stworzBilet(id_biletu:int, id_spektakl:int, cena:float, miejsca:string[]):Bilet
  wyslijBiletMailem(bilet:Bilet, email:string)
}


class Koszyk {
  int id
  float wartosc
  Bilet[] bilety

  usunBiletKoszyk(bilet:Bilet):bool
  dodajBiletKoszyk(bilet:Bilet):bool
}


class PracownikTeatru {
  int id
  string pozycja

  wyslijBiletPoczta(bilet:Bilet, adres:string, adresat:string):bool
  void dodajSpektakl(Spektakl)
  void usunSpektakl(Spektakl)
}

class Teatr {
  int id 
  string nazwa
  string nr_telefonu
  string godziny_otwarcia
  string adres
}

class StronaInternetowa {
  string adres
  int id_teatru
  void wyswietlSpektakle(id_teatru:int)
  void wyswietlAktorow(id_teatru:int)
  void wyswietlKalendarz(id_teatru:int)
  void rozpocznijPlatnosc(id_banku:int, bilety:Bilet[])
  kupBilet(bilet:Bilet, sposob_wysylki:string):bool
  stworzBilet(id_biletu:int, id_spektakl:int, cena:float, miejsca:string[]):Bilet
  wyslijBiletMailem(bilet:Bilet, email:string)
}

Klient -- StronaInternetowa
Klient -- Koszyk
Klient -- Platnosc
Klient -- Bilet
Koszyk o-- Bilet
Koszyk -- Platnosc

PracownikTeatru -- StronaInternetowa

Bank -- Platnosc
Bilet o-- Spektakl

Date -- Spektakl
Spektakl -- StronaInternetowa
StronaInternetowa -- Bilet
PracownikTeatru -- Spektakl

Czlowiek --|> Klient 
Czlowiek --|> PracownikTeatru

Teatr -- StronaInternetowa
@enduml