@startuml SequenceDiagram

actor Użytkownik

Użytkownik -> Klient: otworzStroneGlowna()
activate Klient
'wyswietlSpektakle -> Kup bilet

Klient -> StronaInternetowa: generujBilet(po_tytule)
activate StronaInternetowa
return wyswietlSpektakle()

Klient -> StronaInternetowa: wybierzSpektakl(Spektakl)
activate StronaInternetowa
Klient -> StronaInternetowa: wybierzMiejsca(miejsca[ ])
Klient -> StronaInternetowa: wybierzDate(Date)
StronaInternetowa -> StronaInternetowa: stwórzBilet(...)
return Bilet

Klient -> StronaInternetowa: pokazKoszyk()
activate StronaInternetowa
return Koszyk

Klient -> StronaInternetowa: kupBilet(Bilet, sposob_wysylki)
activate StronaInternetowa
StronaInternetowa -> StronaInternetowa: uzupelnijDane(adres, email, imie, nazwisko)


StronaInternetowa -> Platnosc: rozpocznijPlatnosc(id_banku, bilety)
activate Platnosc
return (metody_platnosci[ ])
StronaInternetowa -> Platnosc: platnoscKarta(kwota, nr_karty, cvv, data_waznosci)
activate Platnosc
return (potwierdzenie)



StronaInternetowa -> StronaInternetowa: wyslijBiletMailem(Bilet,email)
return bilet_kupiony
return powrot_do_strony_glownej
@enduml